#:kivy
<Cat>:
    size: 50, 50
    canvas:
        Color:
            rgba: 0, 1, 0, 1
        Rectangle:
            pos: self.pos
            size: self.size

<Enemy>:
    size: 50, 50
    canvas:
        Color:
            rgba: 1, 0, 0, 1
        Ellipse:
            pos: self.pos
            size: self.size

<CatQuest>:
    cat: cat
    enemy: enemy

    Cat:
        id: cat
    Enemy:
        id: enemy
